name: Sound-of-Silence
channels:
dependencies:
  - numpy
  - matplotlib
  - pytorch::pytorch
  - pip
  - conda-forge::tqdm
  - pandas
  - scipy
  - conda-forge::librosa
  - seaborn
  - contango::python_speech_features
  - conda-forge::pysoundfile
